"""
Mutation Runtime API (Mutation Authority Domain)

Mutation authority domain - canonical mutation topology for all adaptive state mutations.
Authority State: converging → authoritative
Runtime Contract Version: 1.0
"""

from typing import Dict, Any, Optional
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel

from app.services.projection import MutationProjection


router = APIRouter(prefix="/runtime/mutations", tags=["mutation-runtime"])

mutation_router = router


# Pydantic models for API
class MutationRequest(BaseModel):
    """Canonical mutation request."""
    mutation_type: str
    mutation_data: Dict[str, Any]
    context: Optional[Dict[str, Any]] = None


class MutationResponse(BaseModel):
    """Canonical mutation response."""
    mutation_id: str
    mutation_status: str
    event_propagation_status: Dict[str, Any]
    semantic_version: str = "1.0"


class MutationStatusResponse(BaseModel):
    """Mutation status response."""
    mutation_id: str
    mutation_status: str
    event_propagation_status: Dict[str, Any]
    semantic_version: str = "1.0"


# Dependency injection for projection service
def get_mutation_projection() -> MutationProjection:
    """Dependency injection for mutation projection service (wired via DI)."""
    from app.api.v3.dependencies import get_mutation_projection as get_projection
    return get_projection()


@router.post("", response_model=MutationResponse)
async def submit_mutation(
    mutation: MutationRequest,
    projection: MutationProjection = Depends(get_mutation_projection)
):
    """
    Submit canonical mutation.
    
    API: POST /v3/runtime/mutations
    
    All adaptive state mutations must flow through canonical topology.
    NO side-path mutations allowed.
    NO bypass pathways allowed.
    
    Parameters:
    - mutation: Mutation request with mutation_type, mutation_data, context
    
    Returns:
    - MutationResponse with mutation_id, mutation_status, event_propagation_status, semantic_version
    
    Authority State: experimental
    Runtime Contract Version: 1.0
    """
    try:
        # Submit mutation via canonical topology (will implement actual mutation logic)
        # All mutations flow through canonical topology
        # NO side-path mutations
        # NO bypass pathways
        
        # TODO: Implement actual mutation submission via unified_brain and outbox
        mutation_id = "placeholder"  # Will be generated by unified_brain
        
        return MutationResponse(
            mutation_id=mutation_id,
            mutation_status="submitted",
            event_propagation_status={"status": "pending"},
            semantic_version="1.0"
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/status/{mutation_id}", response_model=MutationStatusResponse)
async def get_mutation_status(
    mutation_id: str,
    context: Optional[Dict[str, Any]] = None,
    projection: MutationProjection = Depends(get_mutation_projection)
):
    """
    Get mutation status.
    
    API: GET /v3/runtime/mutations/status/{mutation_id}
    
    Parameters:
    - mutation_id: Mutation identifier
    - context: Optional context (e.g., experiment_run_id for parameterized runtime sessions)
    
    Returns:
    - MutationStatusResponse with mutation_id, mutation_status, event_propagation_status, semantic_version
    
    Authority State: experimental
    Runtime Contract Version: 1.0
    """
    try:
        # Project mutation status via projection service (stateless view)
        status = projection.project_mutation_status(mutation_id)
        
        return MutationStatusResponse(
            mutation_id=status.mutation_id,
            mutation_status=status.mutation_status,
            event_propagation_status=status.event_propagation_status,
            semantic_version=status.semantic_version
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# Export router for registration
mutations_router = router
